name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: f1_season_champions
        ports:
          - 55432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Directory Structure
        run: |
          echo "Current directory:"
          pwd
          echo "Repository root contents:"
          ls -la
          echo "Backend directory contents:"
          ls -la backend
          echo "Find pom.xml:"
          find . -name pom.xml

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Verify Maven Installation
        run: mvn --version

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Check code format with Spotless
        run: mvn -B -ntp spotless:check
        working-directory: ./backend

      - name: Build with Maven (skip tests)
        run: mvn -B -ntp verify -DskipTests
        working-directory: ./backend

      - name: Run Tests with Coverage
        run: mvn -B -ntp verify -Dspring.profiles.active=test
        working-directory: ./backend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          tags: uunlu/f1-v1:${{ env.DOCKER_IMAGE_TAG }},uunlu/f1-v1:latest

      - name: Run Container Security Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.repository }}:latest
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'
